### PR TITLE
feat: prepare to streamline releases with liferay-js-publish (#1334)

### PR DESCRIPTION
**Pull request by wincent**
Test plan: Can't really be 100% sure this will work until we actually test it with a release. I did run `yarn version --minor` but stopped before actually publishing it.

Closes: https://github.com/liferay/alloy-editor/issues/1334

### CODE REVIEW

**Comment by julien** [comment]
Just started reviewing :)

**Comment by wincent** [comment]
Corresponding changes to contributing page on wiki: https://github.com/liferay/alloy-editor/wiki/Contributing/_compare/3503723059ab81cde5fc4d24960821905acc74e1...84b9a9ddfeede478badc7446f88ff058b9243b41

**Comment by wincent** [comment]
And: https://github.com/liferay/alloy-editor/wiki/Contributing/_compare/84b9a9ddfeede478badc7446f88ff058b9243b41...bbcf7cb5c7d66065bb548666caffeeb3d27a2f4d

We can't *really* test this without releasing, so we're just going to have to wait until the next release to be sure.

**Comment by wincent** [comment]
[Green](https://travis-ci.org/liferay/alloy-editor/builds/595017847).

**Pull request merged**
