### PR TITLE
fix: Toolbar is not correctly positioned when editing tables and images within a modal window

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hey guys,

Can you have review this pull request, please?

It is just one more time the case when we need to consider the scroll from top of the uiNode we are passing to the editor.

Closes: https://github.com/liferay/alloy-editor/issues/1466

Thanks.

Regards.

/cc @crodriguezy

### CODE REVIEW

**Comment by wincent** [comment]
@antonio-ortega: Changes look fine at the code level. Hopefully fixing this bug (introduced by [another attempt](https://github.com/liferay/alloy-editor/commit/bef3ce28ff1ba4b5788e511133c3c9e78fcb0549) to fix [a bug](https://github.com/liferay/alloy-editor/issues/1403)) doesn't introduce a different bug that we'll then have to fix 😂. In order to test this, do we need to be on 7.1 (seeing as that's the specific version that [LPS-128401](https://issues.liferay.com/browse/LPS-128401) mentions)?

**Comment by antonio-ortega** [comment]
Hey @wincent ,

In case you want to see it in Master, you can try [this dummy portlet](https://github.com/liferay/alloy-editor/files/6101051/my-mvc-modal-portlet-project_LPS128401.zip) I've just created which shows a button to open Blogs Admin in a modal window.

So the steps you need to follow to reproduce this behavior in Master are:

1. Add `editor.wysiwyg.portal-web.docroot.html.portlet.blogs.edit_entry.jsp=alloyeditor` to your `portal-ext.properties`
2. Start Liferay (master branch)
3. Copy the file `build/libs/com.liferay.docs.mvcportlet-1.0.0.jar` contained in the file I linked above to your `{liferay_home}/deploy` folder.
4. Go to your home page and add that portlet to the page
5. Click on the fancy button
6. Add a new Blog
7. Create a large table so you need to scroll to click on the bottom row.

**Expected behavior**
Toolbar is just above the bottom row

**Actual behavior**
Toolbar is far away from the expected position. As far as you scrolled down.

**Comment by antonio-ortega** [comment]
Btw, we only mentioned 7.1.x in LPS-128401 because in newer branches we are not showing the editor in modal windows in any part of the portal, although as you could see is something you could get with an external development.

**Comment by wincent** [comment]
Thanks @antonio-ortega. Sure beats my usual push-and-pray strategy... testing it out now.

**Comment by wincent** [comment]
Sigh, my liferay-portal instance isn't playing ball with a `yarn add` of my local repo with this PR applied, so to avoid the pain of cutting a preview release, I'm just going to merge this and then immediately test it retrospectively.

**Comment by wincent** [comment]
Release is here: https://github.com/liferay/alloy-editor/releases/tag/v2.12.0 (actually wanted to cut a patch release, but slipped and did a minor instead; no big deal).

Tested in DXP locally: Screenshot 2021-03-08 -151849-jE29OtR1@2x

PR to update liferay-portal: https://github.com/liferay-frontend/liferay-portal/pull/878

**Pull request merged**
