### PR TITLE
Plugin discovery Feature

### PR DESCRIPTION
**Pull request by jbalsas**
Hey guys,

This is the final (hopefully) PR for this. On top of https://github.com/liferay/alloy-editor/pull/718 I've added the final API as:

```javascript
var editor2 = AlloyEditor.editable('editable', {
    extraPlugins: AlloyEditor.Core.ATTRS.extraPlugins.value + ',ae_uibridge,ae_buttonbridge',
        toolbars: {
            styles: {
                selections: [
                    {
                        name: 'text',
                        // Should add the buttons ['Bold', 'Italic', 'Underline', 'link', 'twitter']
                        buttons: AlloyEditor.getButtons(['basicstyles', 'link', 'twitter']),
                        test: AlloyEditor.SelectionTest.text
                    }
                ]
            }
        }
    }
);
```

Thanks! :crossed_fingers:

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Also, following the tutorials in http://alloyeditor.com/guides/ckeditor_plugins/ui_button/, this could be used as:

var selections = AlloyEditor.Selections;
var textButtons = selections[3].buttons; // ['styles', 'bold, 'italic', 'underline', 'link', twitter']
var moreButtons = textButtons.concat('undo'); // ['styles', 'bold, 'italic', 'underline', 'link', twitter', 'undo']

selections[3].buttons = AlloyEditor.getButtons(moreButtons); // should show ['styles', 'bold, 'italic', 'underline', 'link', twitter', 'Undo', 'Redo']

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/357eb014~1...357eb014) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Great job, Chema! This is an awesome feature, a very useful one!
Thank you too, Julien, you did very good job too!

@julien @jbalsas

**Comment by jbalsas** [comment]
victorydance

**Comment by ipeychev** [comment]
:)

**Pull request closed without merging**
