### PR TITLE
Adds MenuButton Bridge Tests

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Hey Chema,

With the rebased master, some of the tests fail? Please check the screenshot:
screen shot 2016-11-27 at 11 08 58 am


Thanks,

**Comment by jbalsas** [comment]
Oops... yeah, need to change valueFn for value again...

I can rebase and resend tomorrow :)

**Comment by jbalsas** [comment]
Rebased and resent to https://github.com/liferay/alloy-editor/pull/643

**Pull request closed without merging**
