### PR TITLE
Fix alignment issues (#206, #386)

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @ipeychev, this PR contains fixes for both #206 and #386 

For #386, I've updated our CKEditor bundle with the [Justify Plugin](http://ckeditor.com/addon/justify). This one doesn't have any dependencies, so it's a nice one :) (The update also bumps CKEditor to `4.5.6`).

The fix for #206 is buried inside the [Image Plugin](http://ckeditor.com/addon/image) which has dependencies with `Dialog` and adds a lot of other stuff such as `doubleclick` events. To avoid using it, I've created a `ae_imagealignment` plugin with just the functionality we need and some improvements such as:
- Support for centering images
- Proper UI updates after changing the alignment

I've added tests for all the alignment buttons, and they are all green in Chrome and Firefox, but I haven't had the chance to test on IE from home.

Let me know what do you think :)

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/0459ead~2...0459ead) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Hey @jbalsas,

This is really cool! The tests passed on IE with a few tweaks, but for [one of them](https://github.com/liferay/alloy-editor/commit/768f98c993dab76062236dbd5cfabf707b090920#diff-503fefcfa091c37ccb5a7107fe3e072dR57) I had to add a condition for IE9. The functionality was working on IE9 too.

Thanks,

**Comment by jbalsas** [comment]
That's awesome! Thanks a lot for taking care of the IE stuff!! :blush: 

I was going over the rest of the issues, and I'm not sure if you'd like something else to go into the next release.

Also, I feel like we're getting to a quite stable situtation in which we can start considering new features rather than just fixes as we've been pretty much doing lately. What do you think?

**Comment by ipeychev** [comment]
I totally agree. There are no more any serious bugs, and we also resolved the most wanted ones (working on the server + Webpack/Browserify), so maybe it is time for version 1.0?

**Comment by jbalsas** [comment]
I think we need to figure out how we want to do the media embed feature (#233) and that's the only thing separating us from a 1.0

I'll try to start looking into it this week.

What do you think?

**Comment by ipeychev** [comment]
Ah, yeah. This one would be good to be there too.
Btw, I think Chrome changed something and now adding images via the camera doesn't work on the demo site for me - there is an 'native' error. Maybe we can fix this one too before 1.0

**Comment by jbalsas** [comment]
Ok, I've created a `1.0.0` milestone and added everything I think we'd need before releasing it. For the camera issues, see #420 and #421.

We're getting close! :wink:

**Pull request merged**
