### PR TITLE
Image link dev

### PR DESCRIPTION
**Pull request by SpencerWoo**
## Issue
https://github.com/liferay/alloy-editor/issues/848

## Solution
For most browsers "check if selection is empty" is sufficient to resolve this issue.

However the Chrome react unmount issue is different as CKEditor injects [7 zero-width space characters].  We test whether the selection is an image in linkSelectionTest to handle this.

## Test
Chrome, IE 11, and FireFox.

gif of issue and fix on Chrome
https://imgur.com/a/h08XgJt

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @SpencerWoo, this is actually breaking the image selection test...

```
 SelectionTest image should detect an image selection FAILED
```

**Comment by SpencerWoo** [comment]
Hi @jbalsas and @antonio-ortega, I've had difficulty figuring out how to proceed with this one so I'd appreciate your input

This PR fails this test https://github.com/liferay/alloy-editor/blob/25151898f9385f09096f05ab7cf30aeea281330d/src/ui/react/test/selection-test.js#L112-L118

The test is always expecting `True` from `imageSelectionTest()` however our change is that we return `False` from `imageSelectionTest()` when `isSelectionEmpty()` is `True`.

We use the `isSelectionEmpty()` check in `imageSelectionTest()` because

- it is `False` when the image is selected (has a toolbar)
- it is `True` after the user confirms/submits the hyperlink (because range[0].collapsed becomes true)

https://github.com/liferay/alloy-editor/blob/25151898f9385f09096f05ab7cf30aeea281330d/src/core/selection-region.js#L202-L209

This `isSelectionEmpty()` check here is also in `textSelectionTest()` however those don't cause textSelection to fail tests.

<hr>

I've had trouble running the tests locally but does it make sense that `imageSelectionTest()` returns `True` when `isSelectionEmpty()` is `True`? 
If it doesn't make sense then should the test be changed to be more specific and pass this case?  
If it does make sense then any input on modifying the fix (using a different check) is appreciated and very helpful.

**Comment by jbalsas** [comment]
Hey @SpencerWoo, I think this shows an issue with these tests, since we aren't properly setting the selection.

I think the correct way to go would be add inside the `getPayload` helper at https://github.com/liferay/alloy-editor/blob/master/src/ui/react/test/selection-test.js#L8 the following:

```javascript
this.editor.get('nativeEditor').getSelection().selectElement(element);
```

That's likely going to make other tests fail and/or introduce some changes, so a more localized fix could be something like:

```javascript
it('should detect an image selection', function() {
    var nativeEditor = this.editor.get('nativeEditor');

    var element = nativeEditor.element.findOne('#editable');

    this.editor.get('nativeEditor').getSelection().selectElement(element);

    var payload = getPayload.call(this, element);

    assert.isTrue(imageTest(payload));
});
```

Can you work around with this and see how it looks?

Thanks!

**Comment by jbalsas** [comment]
I'll actually go ahead and push the second option so we can get a release out the door!

**Pull request merged**
