### PR TITLE
React UI update (#103, #104, #106, #107)

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey Iliyan, I pushed the new commit with the positioning fixes. I've done some refactors to the mixins to reuse as much code as possible.

Let me know what you think!

**Comment by jbalsas** [comment]
Hey Iliyan, I've pushed one more commit with the implementation of most of the buttons. After this, we're just missing the TwitterQuote (#109) and the behaviour change for the Link button (#108).

I'll start working on those on monday, but I wanted to know if you like what's in here or if I should do any changes before going any further.

Thanks!

**Comment by ipeychev** [comment]
Okay, Chema, great! I will process these for sure till Monday. Thanks :+1:

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
