### PR TITLE
New Skin infrastructure

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @ipeychev,

This introduces a new skin infrastructure and then builds on top of that the new Atlas skin.

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @dpobel, if I remember correctly, you mentioned that you had some custom css in your project. Are you building a custom skin based on ours or just laying some css on top? 

The details of what we want to accomplish is described in #288. In addition, you can check how we will be creating skins from now on in [this commit](https://github.com/jbalsas/alloy-editor/commit/c073f38257d4be216ea8dae64e0362b93dc5cd7d).

We plan on shipping this for 0.4 and we'd like to get your feedback about this change and how it may affect you.

**Comment by dpobel** [comment]
Hi @jbalsas 

first thanks for the ping :) Indeed, we are building our own skin based on the ocean one (well, for now we don't change much things but we will in a very near future like next week :)). So the new skin structure is fine for me, of course I'll have to change some code/scripts on our side but introducing this change in a 0.4.0 will give me the time to upgrade properly. It'll also be a good opportunity to improve the custom skin generation on our side because it's very tricky at the moment (and depending on the amount of markup changes our currently generated AlloyEditor CSS might even still work).

**Comment by jbalsas** [comment]
Glad to know, @dpobel :)

The generated css should be exactly the same after this change. We've only restructured the sources so it can be extended more easily.

Let us know if this works for you!

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/decf115~2...decf115) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
