### PR TITLE
Check if editable is not null

### LINKED ISSUE #680: Alloy Editor option not get enabled
Hi,
Sometimes alloy editor ( i.e. + icon ) option is not get enabled. And on console log it gives an error 
"Uncaught TypeError: Cannot read property '$' of undefined
    at t._setUIHidden (alloy-editor-all-min.js:880)
    at t.<anonymous> (alloy-editor-all-min.js:880)"

On refresh page, Alloy Editor ( i.e. + icon ) option get enabled.

I have checked on Alloy editor Demo as well.
Attaching a screen shot for reference.
console_log

### PR DESCRIPTION
**Pull request by julien**
Fixes #680

### CODE REVIEW

**Comment by julien** [comment]
@ipeychev Thanks for the help. Ok I'll have a look.

**Comment by julien** [comment]
hi @ipeychev ,

So I changed this:

```javascript
if (!editable) {
    return;
}
```

For this:

```javascript
if (!editable) {
    this.setState({
        hidden: true
    });
}
````

The issue is that the following line with this code:

```javascript
var res = (editable.$ === target) || editable.contains(targetNode) ||
               (new CKEDITOR.dom.element(domNode)).contains(targetNode);
```

Is executed and since `editable` is `undefined` we still get the following error:

```
Uncaught TypeError: Cannot read property '$' of undefined
    at Constructor._setUIHidden (alloy-editor-all.js:36599)
    at Constructor.<anonymous> (alloy-editor-all.js:36363)
```

I agree it would be better not to have more than one exit branch.

What do you think about this change:

```javascript          
if (domNode) {
    var editable = this.props.editor.get('nativeEditor').editable();
    var targetNode = new CKEDITOR.dom.node(target);
    
    if (editable) {
        var res = (editable.$ === target) || editable.contains(targetNode) ||
                        (new CKEDITOR.dom.element(domNode)).contains(targetNode);

        if (!res) {
            this.setState({
                hidden: true
            });
        }
    }
}
```

It seems to fix the issue as well but adds an `if` statement.

Thanks

**Comment by ipeychev** [comment]
Hey @julien,

I meant code like this:
```
if (!editable) {
    this.setState({
        hidden: true
    });
} else {
  var res = (editable.$ === target) || editable.contains(targetNode) ||
      (new CKEDITOR.dom.element(domNode)).contains(targetNode);

  if (!res) {
      this.setState({
          hidden: true
      });
  }
}
```

In this case we always do `setState`. In the original proposed code there was an exit without setting it.

**Comment by julien** [comment]
@ipeychev, my bad sorry for the confusion.

That actually works fine.
I'll update the PR

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/d1fde5d~1...d1fde5d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
@ipeychev thanks!

**Pull request closed without merging**
