### PR TITLE
[TS] LPS-84123

### PR DESCRIPTION
**Pull request by arthurchan35**
See https://github.com/ckeditor/ckeditor-dev/blob/master/plugins/autolink/plugin.js for example

### CODE REVIEW

**Comment by arthurchan35** [comment]
@jbalsas

**Comment by arthurchan35** [comment]
@antoniopol06 @ambrinchaudhary @diegonvs @ipeychev 
Hi guys, I heard Chema is OOTO right now, can someone help review this pull request? It's a customer issue, so we want to have it complete ASAP.

Thanks

**Comment by diegonvs** [comment]
Hey @arthurchan35, to maintain a better description for non-liferay workers, could you improve the pull request description?

**Comment by diegonvs** [comment]
I'm taking a look right now 😄

**Comment by diegonvs** [comment]
LGTM! What do you think @matuzalemsteles?

**Pull request merged**
