### PR TITLE
fix(a11y): add aria-label and title attributes for the audio and video button (#1281)

### PR DESCRIPTION
**Pull request by rolandpakai**
Please check my fix and push it into a new release.

### CODE REVIEW

**Comment by wincent** [comment]
Code looks good to me.

So if we merge this, it will go into v2.0.8, and from there we can put it in the liferay-portal "master" branch and it will get backported (presumably not by us) to 7.2.

7.1 also has Alloy 2.x ([currently, 2.0.6](https://github.com/brianchandotcom/liferay-portal/blob/cceeef9ee73f2dfde26390be6c9261cc3a5c459d/modules/apps/frontend-editor/frontend-editor-alloyeditor-web/package-lock.json#L671)), so it could be backported there too.

7.0 is on Alloy 1.x ([currently, 1.5.24](https://github.com/brianchandotcom/liferay-portal/blob/65eebad7c1b746b0e5c02cc523f703bc76953058/modules/apps/foundation/frontend-editor/frontend-editor-alloyeditor-web/package-lock.json#L8)). Would the same or a similar change need to be applied in the 1.x branch, @rolandpakai?

**Comment by rolandpakai** [comment]
Sound like a plan!
Please let me knonw when it is released in v2.0.8.

After that i can create a LPS for upgrading it on Master.

Thanks, Roland

**Comment by rolandpakai** [comment]
Hi @wincent 

could you please push this forward?

Thanks, Roland

**Comment by wincent** [comment]
Sorry about the delay @rolandpakai. One more PR to go after this and we can release.

**Pull request merged**
