### PR TITLE
More exciting README!

### PR DESCRIPTION
**Pull request by dandv**

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/55950b8~1...55950b8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Hey @dandv,

Thanks for your contribution! Please note for every commit we need an issue to be created [here](https://github.com/liferay/alloy-editor/issues). Then, in the commit we say:
`Fixes #123` and GitHub closes the issue automatically.
In this way we can track the commits and associate them with the issues. After that, in the milestones we automatically can track which issues went to each release.

Thanks,

**Comment by dandv** [comment]
OK, noted.

**Pull request closed without merging**
