### PR TITLE
Convert widgets on paste

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Iliyan!

This is an updated PR for the embed functionality. As we discussed, it is based on my prior simplified work (no ckeditor plugins other than `widget`). It includes:

- JSONP tool
- Embed plugin
    - AE_Embed Widget definition
    - Embed command
    - Paste handler (I attributed that one to you)
- `Embed` and `EmbedEdit` buttons for the toolbars (same structure as `Link` and `LinkEdit`)
- A new selection and selectiontest for embed elements

There are still some rough edges when editing existing widgets and maybe we could have a better encapsulation for how we can detect if an embed element is selected.

I'll be out of office (and all communication) until Tuesday, so feel free to apply any changes you consider reasonable :relaxed:

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/d316752~3...d316752) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Hey Chema,

This is really cool, we finally have it!
I did some minor source formatting, and there are really some things to improve :) You mentioned the editing, but deleting of a media by pressing back button is problematic too - instead to be deleted, the browser navigates back to the previous page :)
However, in general it works, so merging it!

Thanks,

**Comment by jbalsas** [comment]
Oh, I forgot to add that it's also possible to trigger the embed URL toolbar pressing `CTRL + SHIFT + L` :wink: 

Yeah, I think we have some work to around editing the widgets (this is the first time I played around with this), but looks like we're on the right track.

Thanks a lot for all the work and effort you're still dedicating to this!!

**Pull request closed without merging**
