### PR TITLE
Pass active style to component to check if it was selected.

### PR DESCRIPTION
**Pull request by antoniopol06**

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Hey Antonio,

This is OK, but could you squash it, please? I don't see why 5 commits are needed, one should be enough.
Usually one commit is preferred, because bisecting and rolling back is easier.

Thanks,

**Comment by antoniopol06** [comment]
Hi @ipeychev !

I pushed again with only one commit.

Thanks!

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/d5aaff0~1...d5aaff0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
