### PR TITLE
fix: move drag handler to ensure visible even when image on top line (#1316)

### PR DESCRIPTION
**Pull request by gregory-bretall**
Closes: https://github.com/liferay/alloy-editor/issues/1316

Let me know if you think this is the correct approach or if we want to do something change the z-index of the drag handler.

### CODE REVIEW

**Comment by wincent** [comment]
Taking this for a test-drive now on the Windows laptop here.

**Comment by wincent** [comment]
The top/left doesn't seem to have any effect in my testing on IE 11 on Windows.

Sin título

I'm seeing `top: 0` and `left: 15px`, and the handle is exactly where it was before, partially obscured.

Any ideas what could explain that?

**Comment by duracell80** [comment]
There has to be a different way of thinking here to break out of the difficulties. Why does it have to be at the top? Can't the position of this icon be on the right center of the image?

Then if the image is aligned right switch the position of the icon to the left center?

**Comment by duracell80** [comment]
It's also very small ... I have users that are not very dexterous that struggle with drag and dropping DXP portlets with a mouse.

I have users  that edit content without a mouse because they are in a meeting on a laptop with a touchpad because they don't have a wireless mouse and the mouse is on their desk ... There needs to be some form of user feedback afforded to developers because that would be the only way to see usability improvements with this editor.

We also have many wireless mouses left in meeting rooms so if a user has lost their mouse they can only fall back into their trackpad.

**Comment by wincent** [comment]
Given the doubts about this being the right approach, we're going to close this one.

**Pull request closed without merging**
