### PR TITLE
Moved the contenteditable test to the selection test method

### PR DESCRIPTION
**Pull request by dpobel**
A check against the `isContentEditable` property of the target element was added in the Styles toolbar render method to avoid letting the user style a non editable element. In most cases that's perfectly fine but if you use the widget CKEditor plugin this becomes a problem because this plugin wraps the widget HTML element in a non editable element while you might still want to be able to style the widget with some (custom) buttons.

~~To workaround this problem, this patch adds the support for an optional `canStyleElement` config property in the Styles toolbar so that it's possible to pass a custom function to decide whether the element can be styled or not.~~

~~This does not break any tests and if the approach is OK, I'll of course add some unit tests for that feature.~~

The new version of this patch moves the content editable check to the selection test methods.

### CODE REVIEW

**Comment by dpobel** [comment]
Hi @ipeychev (glad you're still around :))

I already use several custom `test` functions to handle various types of selection but in the case where the user gives the focus to a widget the test function is not even called because of the condition on `isContentEditable` in the very beginning of the `render` method. 
That said, I see your point and I kind of agree. So maybe a better solution would be to move the `isContentEditable` check in the existing test functions and let the custom ones decide whether the content editable property really matters ?

**Comment by ipeychev** [comment]
Hey @dpobel

Yes, I'm around. I left Liferay, but AlloyEditor is in my heart so I'm going to contribute to it as much as possible. Moreover, I'm still the maintainer.

So, about the issue, I think this makes sense. Let's move it inside the test functions. Are you willing to make this change?

Thanks,

**Comment by dpobel** [comment]
yes, I'll try to work on that today, thanks for your feedback.

**Comment by dpobel** [comment]
I updated the patch. While I'm working on the unit tests, I would be happy to get some feedback.

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dpobel** [comment]
I finished implementing the unit tests also did the optimizations suggested by @ipeychev. I guess this is ready for a final review and hopefully a merge :)

**Comment by ipeychev** [comment]
Great, @dpobel, thanks!
Just to note: we will be able to merge this PR probably in a few days - we are in process of updating the permissions to the repo. Nothing scary.

**Comment by andrerom** [comment]
:+1: 
@ipeychev When merged, will there be possibility to get this as part of a tag some time soon as well?

**Comment by ipeychev** [comment]
Yeah, version 0.6 will be released after that!

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
@dpobel 

Great work, thanks! There is a test, which fails on IE (9, 10 and 11). It is [this](https://github.com/ezsystems/alloy-editor/commit/95c86e8f656e909ff2c8999be96b277132e143bd#diff-f962a7400f899491a2fe2c09979386a5R180) one. Does it pass for you?

Thanks,

**Comment by dpobel** [comment]
:( I'm working on Linux so I did not run the test in IE (my mistake). I'm gonna setup a VM and try to see what's going on.

**Comment by dpobel** [comment]
https://msdn.microsoft.com/en-us/library/ms537837%28v=VS.85%29.aspx
> Though the TABLE, COL, COLGROUP, TBODY, TD, TFOOT, TH, THEAD, and TR elements cannot be set as content editable directly [...]

so I have to workaround that somehow

**Comment by ipeychev** [comment]
Okay, great, check if you can figure it out, I don't have a suggestion on top of my head.

**Comment by dpobel** [comment]
So I added a `isEditable` method in `CKEDITOR.Table` and use in the test selection for table. But this was only tested in IE11 but hopefully it works in IE9 and IE10.

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/4504257~2...4504257) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Great job @dpobel!
:+1:

**Pull request closed without merging**
