### PR TITLE
Fixes #924 Add four drag handles for image resizing

### LINKED ISSUE #924: IE11 needs four drag handles when resizing an image
## Issue
When resizing an image within AlloyEditor, IE11 only has one resize handle while other browsers (Chrome, Firefox) have four.
https://issues.liferay.com/browse/LPS-87613

## Reproduce
1) Open IE11.
2) Add a blog entry.
3) Insert an image and resize it. Note the single drag handle on the image.
4) Open Firefox/Chrome and redo steps 2-3. Note that the image has 4 drag handles, one on each corner.

**Expected Result**: All browsers exhibit the same behavior with 4 drag handles around each image in AlloyEditor.
**Actual Results**: In IE11 only one drag handle is present.

## Acceptance Criteria
All browsers exhibit the same behavior with 4 drag handles around each image in AlloyEditor.

### PR DESCRIPTION
**Pull request by diana-lin**
## Prelude
Currently, IE11 only has one resize handle when resizing an image within AlloyEditor while other browsers (Chrome, Firefox) have four.  The task at hand is to implement resizing for IE11 such that it has a total of four drag handles and behaves in the same way as other browsers.
## Issue
https://github.com/liferay/alloy-editor/issues/924

## Solution

- Add styling for the four drag handles on the image resizer (one drag handle on each corner).  
- Add four drag handles as child elements of the image resizer, each with its proper CSS style
     - `factorX` and `factorY` can be either +1 or -1, and they take into account which drag handle is being used.
     - Height and width adjustment with `adjustToX()` and `adjustToY()` methods use `factorX` and `factorY` to determine whether to enlarge or shrink an image.
- No longer need to consider left, center, or right alignment since resizing behaves the same way

## Test
This fix has been tested on Internet Explorer 11, the main environment where we use dragresize_ie11.js.

### CODE REVIEW

**Comment by julien** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by diana-lin** [comment]
Hi @julien,

I will be closing this PR since it causes misplaced drag handles when testing on alloy-editor.  I have sent an updated PR https://github.com/liferay/alloy-editor/pull/934 to fix this issue.

**Comment by duracell80** [comment]
Could the functionality be re-tested in IE using the following code? I'm seeing an issue where the image is being distorted when resizing, maybe because there is a HTML attribute set for width that is restraining the width dimension from properly being 1:1 ratio, in this example.

`<a href="http://www.example.com></a>"`

**Comment by diana-lin** [comment]
Hi @duracell80,

Thank you for bringing this to our attention.  I have created a ticket that addresses this issue.  It can be tracked here: https://issues.liferay.com/browse/LPS-90100.

**Pull request closed without merging**
