### PR TITLE
Restore original keystrokes on component unmount

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @ipeychev, this is a possible solution for #422. I tried several approaches, like creating bookmarks that didn't really work out.

In the end, I thought about this, and in my opinion it has turned out to be quite clean and nice. What do you think?

### CODE REVIEW

**Comment by jbalsas** [comment]
(adding tests...)

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/cd851e9~2...cd851e9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
This is really cool, Chema!

**Pull request closed without merging**
