### PR TITLE
Set contenteditable=false on editor destroy() when enableContentEditable is true

### PR DESCRIPTION
**Pull request by mattleff**
This complements the [behavior](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/adapter/alloy-editor.js#L27-L29) on editor creation.

### CODE REVIEW

**Comment by ipeychev** [comment]
Hey @mattleff,

Thank you for the contribution! This PR looks good, some note about the commit rules we have:
1. Each commit should be associated with an issue. We do that by adding `Fixes #xxx` in the commit message. In this case we can track any comments related to the issue, etc.
2. The commits should have tests, except if technically impossible. We do have tests for destroying the editor, you may add another one which covers the change in your PR.

Thanks again for the contribution!

Iliyan

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/64d7565~3...64d7565) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Okay, I added the needed tests, but please the next time send us PR with tests. If you don't know how to do them, feel free to ask for help.

Thanks,

**Comment by mattleff** [comment]
@ipeychev Sorry I hadn't had a chance to work on unit tests! Do you have a page that explains how to run the unit tests? I have a couple more pulls I'd like to send and I can do the unit tests if I know how.

**Comment by ipeychev** [comment]
Hey @mattleff,

The tests we run simple with with `gulp test`. I have on my machine (Mac) installed VMs for all the supported IE versions. I used `ievms` to [install]((https://github.com/xdissent/ievms#installation)) them.

Hope that helps!

**Pull request closed without merging**
