### PR TITLE
ITI-129 - Replace CKEditor with most recent version (4.7.3)

### PR DESCRIPTION
**Pull request by vbence86**
## Prelude
AlloyEditor currently uses CKEditor 4.0 version as its underlaying content manipulation tool that is now out of date and CKEditor 4.7.x must be integrated as a replacement.

## Issue
[IFI-129](https://issues.liferay.com/browse/IFI-129)

## Solution
Replaced CKEditor 4.0 with CKEditor 4.7.3.

## Test
Ran automated test scenarios.

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @vbence86, thanks for sending this over!

It seems tests and basic behaviour is working, but I'm seeing errors on the console because of the CKEditor@4.7 Plugin management updates:

screen shot 2017-11-22 at 12 44 08

**Comment by jbalsas** [comment]
See https://github.com/ckeditor/ckeditor-dev/issues/654

**Comment by andrerom** [comment]
Ok, pity, but good to know.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/liferay/alloy-editor/pull/805. [See changes here.](https://github.com/liferay/alloy-editor/compare/a7f47dcc~1...a7f47dcc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
I've hacked a workaround and I'm testing it in #805

**Pull request closed without merging**
