### PR TITLE
when stream.stop doesnt exist, using stream.getVideoTracks and it stop all of them.

### PR DESCRIPTION
**Pull request by antoniopol06**

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Hey @antoniopol06,

Thanks for your PR!
We have a rule how to send and accept PR in this project - there should be an issue and for this issue one or more PR can be associated. In this issue we describe the problem, and provide solution. These issues then go to the release log when we release a new version. In this case there is a PR, but no issue and because I am out of context, I don't have an idea what is the problem, on which browser does that happen and why do we need this change.
In this case I created the [issue](Chrome deprecated MediaStream.stop() method #443), please keep that in mind for the next time.

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/fd3aacc~2...fd3aacc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by antoniopol06** [comment]
Hi @ipeychev!

I wrote in the description that fixes #420 but you are right and the next time I will describe better the PR.

**Comment by ipeychev** [comment]
Great! And thanks for the improvement!

**Pull request merged**
