### PR TITLE
Sets editor property before potentially start the render phase

### PR DESCRIPTION
**Pull request by jbalsas**
This is a potential fix for #724. The code path is not yet tested because we didn't find a proper way to test the `LoadLanguageResources` path, if I remember correctly.

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
@ipeychev, pushed changes discussed in https://github.com/liferay/alloy-editor/issues/724

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/3a35038a~1...3a35038a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
