### PR TITLE
Y position of toolbar to render it, now we consider if the content has overflow customization to calculate the proper Y value

### PR DESCRIPTION
**Pull request by antoniopol06**

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey @ipeychev, could we release a new version after this gets merged?

Thanks!

**Comment by ipeychev** [comment]
Sure, probably this weekend.

Thanks,

**Comment by jbalsas** [comment]
Awesome, thanks! 

We'll try to squeeze one more fix in, then 😉

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/5472bf7~2...5472bf7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
