### PR TITLE
ButtonKeystroke (#417, #141)

### LINKED ISSUE #141: ReactUI keyboard shortcuts won't refresh UI
In ReactUI, when executing commands via keyboard shortcuts, the UI doesn't refresh immediately.

__Steps to reproduce:__
1.- Select a text
2.- Click CMD(CTRL) + B to make it bold
3.- Don't release the CMD(CTRL) key (edited)

__Expected:__
The text to become bold and the bold button to become active

__Actual result:__
The text becomes bold but the button remains inactive

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @ipeychev, this adds the requested feature in #417. As a bonus, I've applied the mixin to the `bold`, `italic` and `underline` buttons to fix #141.

I'm from home now, so I've only been able to verify that the tests pass on Chrome and Firefox...

What do you think?

### CODE REVIEW

**Comment by jbalsas** [comment]
Iliyan, I've also pushed simple tests for some of the buttons. I'll try to start covering the rest whenever I have some time.

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/f64d214~2...f64d214) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
This is really cool, Chema!

**Comment by ipeychev** [comment]
Also, the tests were passing on all IE browsers!

**Comment by jbalsas** [comment]
:dancer:

**Pull request merged**
