### PR TITLE
fix(firefox): broken table toolbar (#1283)

### PR DESCRIPTION
**Pull request by rolandpakai**
Plesae check my fix and release it in 1.5.25

Thanks, Roland

The fix was created based on this: https://github.com/liferay/alloy-editor/commit/8d2a3f7ef3e708aa091d54f73e77fa2bca01af11

### CODE REVIEW

**Comment by wincent** [comment]
I see CI is going to be broken on the 1.x branch until we fix this:

```
11 07 2019 08:25:57.494:ERROR [launcher.sauce]: Can not start chrome (OS X 10.11)
  Failed to start Sauce Connect:
  11 Jul 08:25:57 - Response: {"error": "Your Sauce Connect version (4.4.0) is no longer supported. Please download the latest version from https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Proxy."}.
```

**Comment by rolandpakai** [comment]
Thanks @gregory-bretall !
How/Who can fix that ?

**Comment by rolandpakai** [comment]
Hi @wincent 

could you please push this forward?

Thanks, Roland

**Comment by wincent** [comment]
> How/Who can fix that ?

```
Your Sauce Connect version (4.4.0) is no longer supported.
```

Maybe it is a simple matter of updating a dependency. PRs to master aren't complaining, so I am hopeful.

**Comment by wincent** [comment]
@rolandpakai: Ok, I fixed CI in https://github.com/liferay/alloy-editor/pull/1292 — and rebased this on top of it. Seeing as this was targeting the wrong branch ("1.x-stable" instead of "1.x"), I pushed it to a new PR (https://github.com/liferay/alloy-editor/pull/1293) instead of force-pushing to this one.

**Comment by rolandpakai** [comment]
Thank you very much Greg! :)

**Pull request closed without merging**
