### PR TITLE
chore: prepare v1.5.28 release

### PR DESCRIPTION
**Pull request by wincent**
Just a draft PR to see CI green before cutting release.

### CODE REVIEW

**Comment by wincent** [comment]
Finally got a green build: https://travis-ci.org/github/liferay/alloy-editor/builds/713730686

Soooooo flaky.

**Comment by dew326** [comment]
Hi @wincent, I think the compiled files in `dist` catalog are missing: https://github.com/liferay/alloy-editor/tree/v1.5.28/dist
the same case is for `1.5.27` and `1.5.26`, last version that has minified files is `1.5.25`.

**Comment by wincent** [comment]
> Hi @wincent, I think the compiled files in `dist` catalog are missing: https://github.com/liferay/alloy-editor/tree/v1.5.28/dist
> the same case is for `1.5.27` and `1.5.26`, last version that has minified files is `1.5.25`.

@dew326: If you think this is broken, can you file a separate issue for this? However, before you do so, note that it may not actually be a bug. We [intentionally Git-ignore those files](https://github.com/liferay/alloy-editor/blob/v1.5.28/dist/.gitignore). If you install the published package and inspect its contents, you should see something like this:

```
tmp.bBDxW058! ❯ yarn init -y && yarn add alloyeditor@1.5.28                                                                           3.14s /private/var/folders/yc/1x2y2qld1g95tvtjpd89hdrm0000gp/T/tmp.bBDxW058
yarn init v1.22.4
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
✨  Done in 0.04s.
yarn add v1.22.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ alloyeditor@1.5.28
info All dependencies
└─ alloyeditor@1.5.28
✨  Done in 3.23s.
tmp.bBDxW058 ❯ tree node_modules/alloyeditor/dist                                                                                     4.01s /private/var/folders/yc/1x2y2qld1g95tvtjpd89hdrm0000gp/T/tmp.bBDxW058
node_modules/alloyeditor/dist
├── alloy-editor
│   ├── BREAKING_CHANGES.md
│   ├── CHANGELOG.md
│   ├── CONTRIBUTING.md
│   ├── LICENSE.md
│   ├── README.md
│   ├── alloy-editor-all-min.js
│   ├── alloy-editor-all.js
│   ├── alloy-editor-core-min.js
│   ├── alloy-editor-core.js
│   ├── alloy-editor-no-ckeditor-min.js
│   ├── alloy-editor-no-ckeditor.js
│   ├── alloy-editor-no-react-min.js
│   ├── alloy-editor-no-react.js
│   ├── assets
│   │   ├── alloy-editor-atlas-min.css
│   │   ├── alloy-editor-atlas.css
│   │   ├── alloy-editor-moono-min.css
│   │   ├── alloy-editor-moono.css
│   │   ├── alloy-editor-ocean-min.css
│   │   ├── alloy-editor-ocean.css
│   │   └── fonts
│   │       ├── alloyeditor-atlas.eot
│   │       ├── alloyeditor-atlas.svg
│   │       ├── alloyeditor-atlas.ttf
│   │       ├── alloyeditor-atlas.woff
│   │       ├── alloyeditor-default.eot
│   │       ├── alloyeditor-default.svg
│   │       ├── alloyeditor-default.ttf
│   │       ├── alloyeditor-default.woff
│   │       ├── alloyeditor-moono.eot
│   │       ├── alloyeditor-moono.svg
│   │       ├── alloyeditor-moono.ttf
│   │       ├── alloyeditor-moono.woff
│   │       ├── alloyeditor-ocean.eot
│   │       ├── alloyeditor-ocean.svg
│   │       ├── alloyeditor-ocean.ttf
│   │       └── alloyeditor-ocean.woff
│   ├── ckeditor.js
│   ├── config.js
│   ├── contents.css
│   ├── lang
│   │   ├── _translationstatus.txt
│   │   ├── af.js
│   │   ├── alloy-editor
│   │   │   ├── af.js
│   │   │   ├── ar.js
│   │   │   ├── bg.js
│   │   │   ├── bn.js
│   │   │   ├── bs.js
│   │   │   ├── ca.js
│   │   │   ├── cs.js
│   │   │   ├── cy.js
│   │   │   ├── da.js
│   │   │   ├── de.js
│   │   │   ├── el.js
│   │   │   ├── en-au.js
│   │   │   ├── en-ca.js
│   │   │   ├── en-gb.js
│   │   │   ├── en.js
│   │   │   ├── eo.js
│   │   │   ├── es.js
│   │   │   ├── et.js
│   │   │   ├── eu.js
│   │   │   ├── fa.js
│   │   │   ├── fi.js
│   │   │   ├── fo.js
│   │   │   ├── fr-ca.js
│   │   │   ├── fr.js
│   │   │   ├── gl.js
│   │   │   ├── gu.js
│   │   │   ├── he.js
│   │   │   ├── hi.js
│   │   │   ├── hr.js
│   │   │   ├── hu.js
│   │   │   ├── id.js
│   │   │   ├── is.js
│   │   │   ├── it.js
│   │   │   ├── ja.js
│   │   │   ├── ka.js
│   │   │   ├── km.js
│   │   │   ├── ko.js
│   │   │   ├── ku.js
│   │   │   ├── lt.js
│   │   │   ├── lv.js
│   │   │   ├── mk.js
│   │   │   ├── mn.js
│   │   │   ├── ms.js
│   │   │   ├── nb.js
│   │   │   ├── nl.js
│   │   │   ├── no.js
│   │   │   ├── pl.js
│   │   │   ├── pt-br.js
│   │   │   ├── pt.js
│   │   │   ├── ro.js
│   │   │   ├── ru.js
│   │   │   ├── si.js
│   │   │   ├── sk.js
│   │   │   ├── sl.js
│   │   │   ├── sq.js
│   │   │   ├── sr-latn.js
│   │   │   ├── sr.js
│   │   │   ├── sv.js
│   │   │   ├── th.js
│   │   │   ├── tr.js
│   │   │   ├── tt.js
│   │   │   ├── ug.js
│   │   │   ├── uk.js
│   │   │   ├── vi.js
│   │   │   ├── zh-cn.js
│   │   │   └── zh.js
│   │   ├── ar.js
│   │   ├── az.js
│   │   ├── bg.js
│   │   ├── bn.js
│   │   ├── bs.js
│   │   ├── ca.js
│   │   ├── cs.js
│   │   ├── cy.js
│   │   ├── da.js
│   │   ├── de-ch.js
│   │   ├── de.js
│   │   ├── el.js
│   │   ├── en-au.js
│   │   ├── en-ca.js
│   │   ├── en-gb.js
│   │   ├── en.js
│   │   ├── eo.js
│   │   ├── es.js
│   │   ├── et.js
│   │   ├── eu.js
│   │   ├── fa.js
│   │   ├── fi.js
│   │   ├── fo.js
│   │   ├── fr-ca.js
│   │   ├── fr.js
│   │   ├── gl.js
│   │   ├── gu.js
│   │   ├── he.js
│   │   ├── hi.js
│   │   ├── hr.js
│   │   ├── hu.js
│   │   ├── id.js
│   │   ├── is.js
│   │   ├── it.js
│   │   ├── ja.js
│   │   ├── ka.js
│   │   ├── km.js
│   │   ├── ko.js
│   │   ├── ku.js
│   │   ├── lt.js
│   │   ├── lv.js
│   │   ├── mk.js
│   │   ├── mn.js
│   │   ├── ms.js
│   │   ├── nb.js
│   │   ├── nl.js
│   │   ├── no.js
│   │   ├── oc.js
│   │   ├── pl.js
│   │   ├── pt-br.js
│   │   ├── pt.js
│   │   ├── ro.js
│   │   ├── ru.js
│   │   ├── si.js
│   │   ├── sk.js
│   │   ├── sl.js
│   │   ├── sq.js
│   │   ├── sr-latn.js
│   │   ├── sr.js
│   │   ├── sv.js
│   │   ├── th.js
│   │   ├── tr.js
│   │   ├── tt.js
│   │   ├── ug.js
│   │   ├── uk.js
│   │   ├── vi.js
│   │   ├── zh-cn.js
│   │   └── zh.js
│   ├── plugins
│   │   ├── clipboard
│   │   │   └── dialogs
│   │   │       └── paste.js
│   │   ├── dialog
│   │   │   ├── dialogDefinition.js
│   │   │   └── styles
│   │   │       └── dialog.css
│   │   ├── icons.png
│   │   ├── icons_hidpi.png
│   │   ├── pastefromword
│   │   │   └── filter
│   │   │       └── default.js
│   │   ├── pastetools
│   │   │   └── filter
│   │   │       ├── common.js
│   │   │       └── image.js
│   │   └── widget
│   │       └── images
│   │           └── handle.png
│   ├── skins
│   │   └── moono
│   │       ├── dialog.css
│   │       ├── dialog_ie.css
│   │       ├── dialog_ie7.css
│   │       ├── dialog_ie8.css
│   │       ├── dialog_iequirks.css
│   │       ├── editor.css
│   │       ├── editor_gecko.css
│   │       ├── editor_ie.css
│   │       ├── editor_ie7.css
│   │       ├── editor_ie8.css
│   │       ├── editor_iequirks.css
│   │       ├── icons.png
│   │       ├── icons_hidpi.png
│   │       ├── images
│   │       │   ├── anchor.png
│   │       │   ├── arrow.png
│   │       │   ├── close.png
│   │       │   ├── hidpi
│   │       │   │   ├── anchor.png
│   │       │   │   ├── close.png
│   │       │   │   ├── lock-open.png
│   │       │   │   ├── lock.png
│   │       │   │   └── refresh.png
│   │       │   ├── lock-open.png
│   │       │   ├── lock.png
│   │       │   ├── refresh.png
│   │       │   └── spinner.gif
│   │       └── readme.md
│   ├── styles.js
│   └── vendor
│       └── promise.js
└── index.html

21 directories, 212 files
```

**Comment by dew326** [comment]
Yes, I have this when I use yarn but I have old project where we are using Bower and there is an issue.

**Comment by wincent** [comment]
The tool shouldn't make any difference though. Here's the same with `npm`:

```
tmp.dpkSJQcj ❯❯ npm init -y && npm install --save alloyeditor@1.5.28
Wrote to /private/var/folders/yc/1x2y2qld1g95tvtjpd89hdrm0000gp/T/tmp.dpkSJQcj/package.json:

{
  "name": "tmp.dpkSJQcj",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN tmp.dpkSJQcj@1.0.0 No description
npm WARN tmp.dpkSJQcj@1.0.0 No repository field.

+ alloyeditor@1.5.28
added 1 package from 1 contributor and audited 1 package in 3.787s
found 0 vulnerabilities

tmp.dpkSJQcj ❯❯ tree node_modules/alloyeditor/dist
node_modules/alloyeditor/dist
├── alloy-editor
│   ├── BREAKING_CHANGES.md
│   ├── CHANGELOG.md
│   ├── CONTRIBUTING.md
│   ├── LICENSE.md
│   ├── README.md
│   ├── alloy-editor-all-min.js
│   ├── alloy-editor-all.js
│   ├── alloy-editor-core-min.js
│   ├── alloy-editor-core.js
│   ├── alloy-editor-no-ckeditor-min.js
│   ├── alloy-editor-no-ckeditor.js
│   ├── alloy-editor-no-react-min.js
│   ├── alloy-editor-no-react.js
│   ├── assets
│   │   ├── alloy-editor-atlas-min.css
│   │   ├── alloy-editor-atlas.css
│   │   ├── alloy-editor-moono-min.css
│   │   ├── alloy-editor-moono.css
│   │   ├── alloy-editor-ocean-min.css
│   │   ├── alloy-editor-ocean.css
│   │   └── fonts
│   │       ├── alloyeditor-atlas.eot
│   │       ├── alloyeditor-atlas.svg
│   │       ├── alloyeditor-atlas.ttf
│   │       ├── alloyeditor-atlas.woff
│   │       ├── alloyeditor-default.eot
│   │       ├── alloyeditor-default.svg
│   │       ├── alloyeditor-default.ttf
│   │       ├── alloyeditor-default.woff
│   │       ├── alloyeditor-moono.eot
│   │       ├── alloyeditor-moono.svg
│   │       ├── alloyeditor-moono.ttf
│   │       ├── alloyeditor-moono.woff
│   │       ├── alloyeditor-ocean.eot
│   │       ├── alloyeditor-ocean.svg
│   │       ├── alloyeditor-ocean.ttf
│   │       └── alloyeditor-ocean.woff
│   ├── ckeditor.js
│   ├── config.js
│   ├── contents.css
│   ├── lang
│   │   ├── _translationstatus.txt
│   │   ├── af.js
│   │   ├── alloy-editor
│   │   │   ├── af.js
│   │   │   ├── ar.js
│   │   │   ├── bg.js
│   │   │   ├── bn.js
│   │   │   ├── bs.js
│   │   │   ├── ca.js
│   │   │   ├── cs.js
│   │   │   ├── cy.js
│   │   │   ├── da.js
│   │   │   ├── de.js
│   │   │   ├── el.js
│   │   │   ├── en-au.js
│   │   │   ├── en-ca.js
│   │   │   ├── en-gb.js
│   │   │   ├── en.js
│   │   │   ├── eo.js
│   │   │   ├── es.js
│   │   │   ├── et.js
│   │   │   ├── eu.js
│   │   │   ├── fa.js
│   │   │   ├── fi.js
│   │   │   ├── fo.js
│   │   │   ├── fr-ca.js
│   │   │   ├── fr.js
│   │   │   ├── gl.js
│   │   │   ├── gu.js
│   │   │   ├── he.js
│   │   │   ├── hi.js
│   │   │   ├── hr.js
│   │   │   ├── hu.js
│   │   │   ├── id.js
│   │   │   ├── is.js
│   │   │   ├── it.js
│   │   │   ├── ja.js
│   │   │   ├── ka.js
│   │   │   ├── km.js
│   │   │   ├── ko.js
│   │   │   ├── ku.js
│   │   │   ├── lt.js
│   │   │   ├── lv.js
│   │   │   ├── mk.js
│   │   │   ├── mn.js
│   │   │   ├── ms.js
│   │   │   ├── nb.js
│   │   │   ├── nl.js
│   │   │   ├── no.js
│   │   │   ├── pl.js
│   │   │   ├── pt-br.js
│   │   │   ├── pt.js
│   │   │   ├── ro.js
│   │   │   ├── ru.js
│   │   │   ├── si.js
│   │   │   ├── sk.js
│   │   │   ├── sl.js
│   │   │   ├── sq.js
│   │   │   ├── sr-latn.js
│   │   │   ├── sr.js
│   │   │   ├── sv.js
│   │   │   ├── th.js
│   │   │   ├── tr.js
│   │   │   ├── tt.js
│   │   │   ├── ug.js
│   │   │   ├── uk.js
│   │   │   ├── vi.js
│   │   │   ├── zh-cn.js
│   │   │   └── zh.js
│   │   ├── ar.js
│   │   ├── az.js
│   │   ├── bg.js
│   │   ├── bn.js
│   │   ├── bs.js
│   │   ├── ca.js
│   │   ├── cs.js
│   │   ├── cy.js
│   │   ├── da.js
│   │   ├── de-ch.js
│   │   ├── de.js
│   │   ├── el.js
│   │   ├── en-au.js
│   │   ├── en-ca.js
│   │   ├── en-gb.js
│   │   ├── en.js
│   │   ├── eo.js
│   │   ├── es.js
│   │   ├── et.js
│   │   ├── eu.js
│   │   ├── fa.js
│   │   ├── fi.js
│   │   ├── fo.js
│   │   ├── fr-ca.js
│   │   ├── fr.js
│   │   ├── gl.js
│   │   ├── gu.js
│   │   ├── he.js
│   │   ├── hi.js
│   │   ├── hr.js
│   │   ├── hu.js
│   │   ├── id.js
│   │   ├── is.js
│   │   ├── it.js
│   │   ├── ja.js
│   │   ├── ka.js
│   │   ├── km.js
│   │   ├── ko.js
│   │   ├── ku.js
│   │   ├── lt.js
│   │   ├── lv.js
│   │   ├── mk.js
│   │   ├── mn.js
│   │   ├── ms.js
│   │   ├── nb.js
│   │   ├── nl.js
│   │   ├── no.js
│   │   ├── oc.js
│   │   ├── pl.js
│   │   ├── pt-br.js
│   │   ├── pt.js
│   │   ├── ro.js
│   │   ├── ru.js
│   │   ├── si.js
│   │   ├── sk.js
│   │   ├── sl.js
│   │   ├── sq.js
│   │   ├── sr-latn.js
│   │   ├── sr.js
│   │   ├── sv.js
│   │   ├── th.js
│   │   ├── tr.js
│   │   ├── tt.js
│   │   ├── ug.js
│   │   ├── uk.js
│   │   ├── vi.js
│   │   ├── zh-cn.js
│   │   └── zh.js
│   ├── plugins
│   │   ├── clipboard
│   │   │   └── dialogs
│   │   │       └── paste.js
│   │   ├── dialog
│   │   │   ├── dialogDefinition.js
│   │   │   └── styles
│   │   │       └── dialog.css
│   │   ├── icons.png
│   │   ├── icons_hidpi.png
│   │   ├── pastefromword
│   │   │   └── filter
│   │   │       └── default.js
│   │   ├── pastetools
│   │   │   └── filter
│   │   │       ├── common.js
│   │   │       └── image.js
│   │   └── widget
│   │       └── images
│   │           └── handle.png
│   ├── skins
│   │   └── moono
│   │       ├── dialog.css
│   │       ├── dialog_ie.css
│   │       ├── dialog_ie7.css
│   │       ├── dialog_ie8.css
│   │       ├── dialog_iequirks.css
│   │       ├── editor.css
│   │       ├── editor_gecko.css
│   │       ├── editor_ie.css
│   │       ├── editor_ie7.css
│   │       ├── editor_ie8.css
│   │       ├── editor_iequirks.css
│   │       ├── icons.png
│   │       ├── icons_hidpi.png
│   │       ├── images
│   │       │   ├── anchor.png
│   │       │   ├── arrow.png
│   │       │   ├── close.png
│   │       │   ├── hidpi
│   │       │   │   ├── anchor.png
│   │       │   │   ├── close.png
│   │       │   │   ├── lock-open.png
│   │       │   │   ├── lock.png
│   │       │   │   └── refresh.png
│   │       │   ├── lock-open.png
│   │       │   ├── lock.png
│   │       │   ├── refresh.png
│   │       │   └── spinner.gif
│   │       └── readme.md
│   ├── styles.js
│   └── vendor
│       └── promise.js
└── index.html

21 directories, 212 files
```

And here's me downloading the package by hand:

```
tmp.ivibogoa ❯❯❯ wget https://registry.npmjs.org/alloyeditor/-/alloyeditor-1.5.28.tgz
--2020-08-03 14:33:57--  https://registry.npmjs.org/alloyeditor/-/alloyeditor-1.5.28.tgz
Resolving registry.npmjs.org (registry.npmjs.org)... 104.16.23.35, 104.16.19.35, 104.16.21.35, ...
Connecting to registry.npmjs.org (registry.npmjs.org)|104.16.23.35|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2183147 (2.1M) [application/octet-stream]
Saving to: ‘alloyeditor-1.5.28.tgz’

alloyeditor-1.5.28.tgz    100%[=====================================>]   2.08M  1.86MB/s    in 1.1s

2020-08-03 14:33:59 (1.86 MB/s) - ‘alloyeditor-1.5.28.tgz’ saved [2183147/2183147]

tmp.ivibogoa ❯❯❯ tar xzf alloyeditor-1.5.28.tgz
tmp.ivibogoa ❯❯❯ tree package/dist   0.29s /var/folders/yc/1x2y2qld1g95tvtjpd89hdrm0000gp/T/tmp.ivibogoa
package/dist
├── alloy-editor
│   ├── BREAKING_CHANGES.md
│   ├── CHANGELOG.md
│   ├── CONTRIBUTING.md
│   ├── LICENSE.md
│   ├── README.md
│   ├── alloy-editor-all-min.js
│   ├── alloy-editor-all.js
│   ├── alloy-editor-core-min.js
│   ├── alloy-editor-core.js
│   ├── alloy-editor-no-ckeditor-min.js
│   ├── alloy-editor-no-ckeditor.js
│   ├── alloy-editor-no-react-min.js
│   ├── alloy-editor-no-react.js
│   ├── assets
│   │   ├── alloy-editor-atlas-min.css
│   │   ├── alloy-editor-atlas.css
│   │   ├── alloy-editor-moono-min.css
│   │   ├── alloy-editor-moono.css
│   │   ├── alloy-editor-ocean-min.css
│   │   ├── alloy-editor-ocean.css
│   │   └── fonts
│   │       ├── alloyeditor-atlas.eot
│   │       ├── alloyeditor-atlas.svg
│   │       ├── alloyeditor-atlas.ttf
│   │       ├── alloyeditor-atlas.woff
│   │       ├── alloyeditor-default.eot
│   │       ├── alloyeditor-default.svg
│   │       ├── alloyeditor-default.ttf
│   │       ├── alloyeditor-default.woff
│   │       ├── alloyeditor-moono.eot
│   │       ├── alloyeditor-moono.svg
│   │       ├── alloyeditor-moono.ttf
│   │       ├── alloyeditor-moono.woff
│   │       ├── alloyeditor-ocean.eot
│   │       ├── alloyeditor-ocean.svg
│   │       ├── alloyeditor-ocean.ttf
│   │       └── alloyeditor-ocean.woff
│   ├── ckeditor.js
│   ├── config.js
│   ├── contents.css
│   ├── lang
│   │   ├── _translationstatus.txt
│   │   ├── af.js
│   │   ├── alloy-editor
│   │   │   ├── af.js
│   │   │   ├── ar.js
│   │   │   ├── bg.js
│   │   │   ├── bn.js
│   │   │   ├── bs.js
│   │   │   ├── ca.js
│   │   │   ├── cs.js
│   │   │   ├── cy.js
│   │   │   ├── da.js
│   │   │   ├── de.js
│   │   │   ├── el.js
│   │   │   ├── en-au.js
│   │   │   ├── en-ca.js
│   │   │   ├── en-gb.js
│   │   │   ├── en.js
│   │   │   ├── eo.js
│   │   │   ├── es.js
│   │   │   ├── et.js
│   │   │   ├── eu.js
│   │   │   ├── fa.js
│   │   │   ├── fi.js
│   │   │   ├── fo.js
│   │   │   ├── fr-ca.js
│   │   │   ├── fr.js
│   │   │   ├── gl.js
│   │   │   ├── gu.js
│   │   │   ├── he.js
│   │   │   ├── hi.js
│   │   │   ├── hr.js
│   │   │   ├── hu.js
│   │   │   ├── id.js
│   │   │   ├── is.js
│   │   │   ├── it.js
│   │   │   ├── ja.js
│   │   │   ├── ka.js
│   │   │   ├── km.js
│   │   │   ├── ko.js
│   │   │   ├── ku.js
│   │   │   ├── lt.js
│   │   │   ├── lv.js
│   │   │   ├── mk.js
│   │   │   ├── mn.js
│   │   │   ├── ms.js
│   │   │   ├── nb.js
│   │   │   ├── nl.js
│   │   │   ├── no.js
│   │   │   ├── pl.js
│   │   │   ├── pt-br.js
│   │   │   ├── pt.js
│   │   │   ├── ro.js
│   │   │   ├── ru.js
│   │   │   ├── si.js
│   │   │   ├── sk.js
│   │   │   ├── sl.js
│   │   │   ├── sq.js
│   │   │   ├── sr-latn.js
│   │   │   ├── sr.js
│   │   │   ├── sv.js
│   │   │   ├── th.js
│   │   │   ├── tr.js
│   │   │   ├── tt.js
│   │   │   ├── ug.js
│   │   │   ├── uk.js
│   │   │   ├── vi.js
│   │   │   ├── zh-cn.js
│   │   │   └── zh.js
│   │   ├── ar.js
│   │   ├── az.js
│   │   ├── bg.js
│   │   ├── bn.js
│   │   ├── bs.js
│   │   ├── ca.js
│   │   ├── cs.js
│   │   ├── cy.js
│   │   ├── da.js
│   │   ├── de-ch.js
│   │   ├── de.js
│   │   ├── el.js
│   │   ├── en-au.js
│   │   ├── en-ca.js
│   │   ├── en-gb.js
│   │   ├── en.js
│   │   ├── eo.js
│   │   ├── es.js
│   │   ├── et.js
│   │   ├── eu.js
│   │   ├── fa.js
│   │   ├── fi.js
│   │   ├── fo.js
│   │   ├── fr-ca.js
│   │   ├── fr.js
│   │   ├── gl.js
│   │   ├── gu.js
│   │   ├── he.js
│   │   ├── hi.js
│   │   ├── hr.js
│   │   ├── hu.js
│   │   ├── id.js
│   │   ├── is.js
│   │   ├── it.js
│   │   ├── ja.js
│   │   ├── ka.js
│   │   ├── km.js
│   │   ├── ko.js
│   │   ├── ku.js
│   │   ├── lt.js
│   │   ├── lv.js
│   │   ├── mk.js
│   │   ├── mn.js
│   │   ├── ms.js
│   │   ├── nb.js
│   │   ├── nl.js
│   │   ├── no.js
│   │   ├── oc.js
│   │   ├── pl.js
│   │   ├── pt-br.js
│   │   ├── pt.js
│   │   ├── ro.js
│   │   ├── ru.js
│   │   ├── si.js
│   │   ├── sk.js
│   │   ├── sl.js
│   │   ├── sq.js
│   │   ├── sr-latn.js
│   │   ├── sr.js
│   │   ├── sv.js
│   │   ├── th.js
│   │   ├── tr.js
│   │   ├── tt.js
│   │   ├── ug.js
│   │   ├── uk.js
│   │   ├── vi.js
│   │   ├── zh-cn.js
│   │   └── zh.js
│   ├── plugins
│   │   ├── clipboard
│   │   │   └── dialogs
│   │   │       └── paste.js
│   │   ├── dialog
│   │   │   ├── dialogDefinition.js
│   │   │   └── styles
│   │   │       └── dialog.css
│   │   ├── icons.png
│   │   ├── icons_hidpi.png
│   │   ├── pastefromword
│   │   │   └── filter
│   │   │       └── default.js
│   │   ├── pastetools
│   │   │   └── filter
│   │   │       ├── common.js
│   │   │       └── image.js
│   │   └── widget
│   │       └── images
│   │           └── handle.png
│   ├── skins
│   │   └── moono
│   │       ├── dialog.css
│   │       ├── dialog_ie.css
│   │       ├── dialog_ie7.css
│   │       ├── dialog_ie8.css
│   │       ├── dialog_iequirks.css
│   │       ├── editor.css
│   │       ├── editor_gecko.css
│   │       ├── editor_ie.css
│   │       ├── editor_ie7.css
│   │       ├── editor_ie8.css
│   │       ├── editor_iequirks.css
│   │       ├── icons.png
│   │       ├── icons_hidpi.png
│   │       ├── images
│   │       │   ├── anchor.png
│   │       │   ├── arrow.png
│   │       │   ├── close.png
│   │       │   ├── hidpi
│   │       │   │   ├── anchor.png
│   │       │   │   ├── close.png
│   │       │   │   ├── lock-open.png
│   │       │   │   ├── lock.png
│   │       │   │   └── refresh.png
│   │       │   ├── lock-open.png
│   │       │   ├── lock.png
│   │       │   ├── refresh.png
│   │       │   └── spinner.gif
│   │       └── readme.md
│   ├── styles.js
│   └── vendor
│       └── promise.js
└── index.html

21 directories, 212 files
```

So, I don't think there is anything wrong with the published package.

**Comment by dew326** [comment]
I think bower by default doesn't use the NPM library, but it is possible to force download from the direct link so this solved my problem.
Thank you again.

**Pull request closed without merging**
