### PR TITLE
Improve ae-embed plugin widget selection

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @ipeychev, this is a possible fix for #517.

We've changed the way the widgets are selected and handled to let CKEditor handle it in its own way, and figured out a different way to show the toolbar on them.

On top of that, we've also added a remove button to the embed edit button following the pattern on the link one so it is possible to remove a widget from the toolbar.

Thanks!

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Hey Chema,

This is really cool, but right now clicking on the button for adding an embedded media throws an exception? Please see the attached screencast.

Thanks,
bug

**Comment by jbalsas** [comment]
Oh! Forgot to check that one! I was always pasting a url

I'm not at home right now, but I'll take a look as soon as a I get back!

**Comment by ipeychev** [comment]
Great, the rest is cool!

One thing to consider - maybe it will make sense to allow people to set the size of the embedded content. Right now it takes the whole content width and there is no way to change it. In the same time, I'm not sure if we can make it perfect for every provider.
As I see, the response contains the name of the provider - "provider_name": "YouTube" or "provider_name": "Twitter" for example. Maybe we can add such class to the wrapping div, something like `data-provider=YouTube`, so people will be able to style it accordingly? 

Thanks,

**Comment by jbalsas** [comment]
Hey Iliyan!

I've pushed one extra commit with some fixes for the remove button. I've refactored it so it better follows the same pattern as `button-link-edit`.

This has also made me realize we never got around to create tests for this feature, so I'll ask @antoniopol06 to work on that whenever we can.

**Comment by jbalsas** [comment]
Regarding the width and height of the embeds, I remembered you already brought this up on our initial discussion and I never followed on this. I'm really sorry about that 😢 

How about we create an independent feature request for it so we can properly analyze it and tackle it as soon as we can?

I get the feeling that just a class might not be enough. Depending on the media content, it might be necessary to, for example, set the `width` and `height` attributes of the iframe, or maybe even request the embed again if the query supports dimensions as the output might be different.

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/1f354f4~2...1f354f4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Hey Chema and Antonio,

Great, this was cool fix which means it is time to release another minor version!

About setting the size of the embedded content, if you think the class won't be enough, then, sure - let's open a ticket to consider what can be done.

@jbalsas @antoniopol06

**Pull request closed without merging**
