### PR TITLE
Source formatting

### PR DESCRIPTION
**Pull request by antoniopol06**
This [PR](https://github.com/antoniopol06/alloy-editor/pull/6) has a extensive detail to know the context.

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Hey guys,

This project follows some rules for PR:
1. Each PR should have an associated issue with it. The issue should be opened in this repository and it should clearly explain what is the problem and how to reproduce it. Issues, opened in other repositories may be used only as reference.
2. The commit message should say which is the issue it fixes/closes.

Apart from that, the purpose of [this](https://github.com/liferay/alloy-editor/pull/606/commits/9a739dc627fb99ec2e51c0ce1d8de1e0e68ce072) commit is unclear.

Thanks,

**Comment by dustinryerson** [comment]
@zsagia please see @ipeychev's analysis above.

**Comment by antoniopol06** [comment]
Hi guys!!

I created the issue and I sent a new [PR](https://github.com/liferay/alloy-editor/pull/609) with tests 

Let me know if you have questions.

Thanks!

**Comment by zsagia** [comment]
Tanks a lot Antonio. :)


Zsolt Szabo a.k.a. Zsaga

Engineer, Technical Support

Subscription Services | EMEA

Liferay Hungary | Madarász Viktor u. 47., 1138, Budapest, Hungary

**Pull request closed without merging**
