### PR TITLE
Use region.left and region.top instead of nativeEvent.pageX and nativeEvent.pageY. IE doesnt retrieve the correct pageY when you scroll the page.

### PR DESCRIPTION
**Pull request by antoniopol06**

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey Iliyan, we just saw this today, and there were no tests around this part. I see we have the `selectionRegion` plugin covered, so maybe it would be possible to do it here as well, but since you were the one that worked on it mostly, I didn't remember if it would be somewhat very hard...

**Comment by ipeychev** [comment]
Hey Chema,

As I wrote [here](https://github.com/liferay/alloy-editor/issues/425#issuecomment-171076568), I couldn't reproduce this and also with the PR the toolbar appears in the beginning of the selection instead where the mouse was released. Could you please add a screencast?

About the tests on this part, probably those days I had time to cover only the `selectionRegion`, but nothing prevents us to do it now. Looking on it now, the "hardest" part would be to simulate the events in such a way that a proper `selectionData` to arrive, but even if it is, we can mock the `selectionData` and pass the proper regions to test the direction.

Thanks,

**Comment by jbalsas** [comment]
Hey Iliyan, ok, we'll try to start testing the missing parts, so we'll add this to our to-do list.

We'll do some more testing around this to see what's going on...

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/79a6c6c~1...79a6c6c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
:+1: 

Thanks!

**Pull request closed without merging**
