### PR TITLE
Updates test message and adds default case

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @ipeychev, I've rebased and fixed the conflicts. Turns out the test file was conflicting with some previously added ones... I think it's the first time we run into problems by writing too many tests 😂

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Umm, let me see if I understood correctly the issue:
If the **user** passes explicitly `'ae_dragresize` in extraPlugins property, then the drag in IE11 will stop working. Is that correct?
```
var content = new AlloyEditor.editable('myContent', {extraPlugins: 'ae_dragresize'})
```

And why do we do [this](https://github.com/liferay/alloy-editor/pull/728/commits/e6c4abfa40e5d19ad0a8e890850bac131816b43f), user's preferences **always** have precedence?

**Comment by jbalsas** [comment]
Hey Iliyan!

Yeah, on top of user preferences, I think we always want our swap to prevail. We added that so users would only need to add `ae_dragresize` (always) and we'd take care of using the right plugin depending on the browser. Also, in some cases like server-side generated config, they won't even be able to decide which one should they use. That's why we always need to do the replace at the end.

```javascript
if (CKEDITOR.env.ie) {
    editor.config.extraPlugins = editor.config.extraPlugins.replace('ae_dragresize', 'ae_dragresize_ie');
    editor.config.removePlugins = editor.config.removePlugins.replace('ae_dragresize', 'ae_dragresize_ie');
}
```

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/866ebac6~1...866ebac6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Okay... then we can merge this one for now. Thanks!

**Pull request merged**
