### PR TITLE
Use focus event to attach the handleUI listeners and detach them on blur

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @ipeychev, this is a possible fix for #450 

We haven't managed to get the test passing on firefox, though... could you please take a look?

Thanks!

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey @ipeychev, I've added a small `Utils.focusEditor` helper that seems to help with this in Firefox.

What do you think?

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/1e2b324~1...1e2b324) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Great success!
:)

**Pull request closed without merging**
