### PR TITLE
Image center button

### PR DESCRIPTION
**Pull request by ejfrancis**
added a button to align an image to the center of its container

@ipeychev

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/42727d7~3...42727d7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Hey @ejfrancis,

I merged your PR! Thanks for the contribution, we really appreciate it!

A few notes:
1. When we do commits, we always associate the commit with an issue (for example Fixes #322). In this case we know what was the purpose of this commit. We can also follow the comments on the issue and so on.
2. We always add tests in addition to the code. Exceptions are when it is technically impossible to create a test - for example in very complex cases, when simulating such events just does not work. This time I added the tests, but please note in general the PR should come with tests.

Thanks again,
Iliyan

**Comment by ejfrancis** [comment]
:+1:

**Pull request closed without merging**
