### PR TITLE
Clicking on Add image button should only accept images, not any other file types

### PR DESCRIPTION
**Pull request by jssisodiya**
Hey @ipeychev 
I think the input element in button-image.jsx should only accept image type files. So i added accept attribute to file type input for 'Image Button'.

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/eace37d~1...eace37d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jssisodiyaPG** [comment]
Cheers :)

**Comment by jssisodiya** [comment]
Cheers :)

**Pull request closed without merging**
