### PR TITLE
Propagate context in tests

### PR DESCRIPTION
**Pull request by wincent**
All of this in service of: https://github.com/liferay/alloy-editor/issues/1123

This PR contains a bunch of refactoring — individual commit messages contain the explanation — that I did in exploring that issue. I found a bunch of hidden failures due to context not being propagated, and found a related set of problems caused by our test set-up sending over 63 MB(!!!!) of duplicated JS to the browser:

karma_debug_runner

### CODE REVIEW

**Comment by wincent** [comment]
@julien: Marking this one as WIP because while this fixes the majority of the issue; we still have an issue where the initial component loads are causing the `EditorContext` to be re-evaluated many times, not because of `eval` but because the module is being inlined with each file. I think that will be a matter of figuring out the right webpack config changes, but I'll look at that tomorrow.

**Comment by julien** [comment]
Just started reviewing 👀 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by wincent** [comment]
Just updated, but still not ready for review yet. I have one more commit on top of this which I don't think is going to work; I committed it here:

https://github.com/wincent/alloy-editor/commit/9ed7308003b5c0c0406d3f6af2409fa17f7fe48e

([Gist here](https://gist.github.com/wincent/61d649f5eb56e2b6c2540bd4928bb281) for when that link inevitably goes dead.)

I'm now going to try the alternate approach mentioned in that commit.

**Comment by wincent** [comment]
@julien: I think this one is ready now. I'm going to move on to looking at some of the remaining hidden failures, and figuring out why they are hidden...

**Comment by wincent** [comment]
Just rebased to get on top of the latest "master".

**Comment by wincent** [comment]
One last rebase. Got the over-the-shoulder thumbs up from @julien to merge this.

**Pull request merged**
