### PR TITLE
Adds MenuButton Bridge Tests

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by antoniopol06** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
@jbalsas @antoniopol06 

Antionio, are you reviewing this PR? What is its status?

**Comment by jbalsas** [comment]
Hey @ipeychev, I thought you were reviewing it. Since I wrote it, it looks good to me! 😉

**Comment by ipeychev** [comment]
Haha, yeah, but the [last comment](https://github.com/liferay/alloy-editor/pull/643#issuecomment-263532829) is from Antonio, which says "Just started reviewing" :)

**Comment by jbalsas** [comment]
😅😅

He just got the PR to test it and write the tutorials for this feature.

They're in my queue and I'll publish together with the site update after
the release 😊

**Comment by ipeychev** [comment]
Okay then, will get it today.

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/d254ece~2...d254ece) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
