### PR TITLE
fix: correct toolbar misalignment when editor is rendered in modal and the uiNode is provided

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
Github issue: https://github.com/liferay/alloy-editor/issues/1424
[LPS-120361](https://issues.liferay.com/browse/LPS-120361)
Note in order to test in liferay [LPS-120360](https://issues.liferay.com/browse/LPS-120360) has to be applied

Also there is a discussion at [PTR-1918](https://issues.liferay.com/browse/PTR-1918) about why we decided we should fix this in AE.

Please review my change,

Thanks

### CODE REVIEW

**Comment by wincent** [comment]
Thanks @NemethNorbert; taking a look at this now.

**Comment by wincent** [comment]
I updated your commit and pushed to your fork to:

- Fix formatting.
- Retitle commit to satisfy the complaints of the Semantic Pull Request bot.

While I was at it, I copy-pasted some of the useful context from the various Jira tickets to the commit message so that we can easily find it in the future (ie. with `git-blame`).

For future reference, @NemethNorbert, you can fix formatting with `yarn format` (that's what CI was complaining about) and the thing the Semantic PR bot was complaining about was the missing space after the "fix:" in the commit message and the PR title (I edited both).

**Comment by wincent** [comment]
Re-pushed one more time after actually including formatting fixes in the commit.

**Comment by wincent** [comment]
For some reason Travis builds seem to be hanging. I retried one, but the retry is currently 33 minutes and counting...

Running `yarn test:debug` locally but that's a bit flakey for me right now:

Screenshot 2020-09-07 -152727-klWJxQMT@2x

But then again, so is `master`:

Screenshot 2020-09-07 -153053-JxoaWjyw@2x

CI tends to hide some issues... going to give it one last retry.

**Comment by wincent** [comment]
I'm running into difficulty testing this in DXP, probably some weird stuff going on on my machine (note: I'm not even testing it on 7.0, where the bug is reported — I'm just trying to confirm that it doesn't regress anything else on `master`), so I'm going to cut a prerelease so that I can do a bundle-based test from CI at least.

- Prerelease: https://github.com/liferay/alloy-editor/releases/tag/v2.11.14-pre.0
- DXP test here: https://github.com/liferay-frontend/liferay-portal/pull/372

**Comment by wincent** [comment]
Seems to work well in DXP, so I think we can merge this. I would like to address the CI issues, but they are pre-existing, so going to push on before this becomes any more of a time sink.

**Comment by wincent** [comment]
@NemethNorbert: if you want to track when this makes it into a release, subscribe to [this PR](https://github.com/liferay/alloy-editor/pull/1428) from @julien; I figure that will go in real soon (tomorrow?) and we can cut a release after that.

**Comment by NemethNorbert** [comment]
Hey @wincent ,
The PR I supposed to track for the release got rejected and closed. When can I expect a new release with this fix?

Thank you,

**Comment by wincent** [comment]
@julien: What's the status on that one? Will there be a re-roll? If not, we'll do a release anyway for @NemethNorbert.

**Comment by wincent** [comment]
Going to cut a release because the fix for the other one is coming on `NaN`.

**Comment by wincent** [comment]
Release is out: https://github.com/liferay/alloy-editor/releases/tag/v2.11.14

Going to forward this one: https://github.com/liferay-frontend/liferay-portal/pull/389

**Pull request merged**
