### PR TITLE
fix: preserve height style for IE (1.x)

### PR DESCRIPTION
**Pull request by SpencerWoo**
Not certain if the 'backport' procedure is to do 1:1 commits but I've bundled the changes of this section of code into one commit here

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @SpencerWoo, I assume this is for `7.0.x`? I think it should be safe and preferrable at this point to backport the changes to AlloyEditor v2 so we can concentrate there. Since we've had it in `7.1.x` for a while and ironed out the quirks, I'd say this is a realistic option.

What do you think?

**Comment by jbalsas** [comment]
Just to be clear, I'm proposing we move `7.0.x` to `AlloyEditor@2` so we can stop maintaining the `1.x` branch independently :)

**Comment by SpencerWoo** [comment]
Yes, this was for `7.0.x` -- moving `7.0.x` to `AlloyEditor@2` meets my use case and sounds good!

**Comment by wincent** [comment]
> so we can stop maintaining the `1.x` branch independently

source

**Comment by wincent** [comment]
By way of status update, @antonio-ortega has been looking at back-porting v2.x of AlloyEditor to DXP 7.0, which is why this one is sitting here in pending state for now.

**Comment by wincent** [comment]
Backport has been done so we can effectively forget about all 1.x PRs from here on — as long as the fixes go into master/2.x, we're good.

**Pull request closed without merging**
