### PR TITLE
Add linkSchema config to set default protocol to link

### PR DESCRIPTION
**Pull request by antoniopol06**

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Hey @antoniopol06, @jbalsas,

This change makes a lot of sense, however many tests fail? They fail in all browsers, and the interesting is that even the newly created test fail. Please see the following screenshot:
screen shot 2016-02-17 at 9 26 37 pm

Thanks,

**Comment by jbalsas** [comment]
Hey Iliyan, after the tests, the editor was not being properly initialized with the attributes (and we also failed to produce a sensible default). @antoniopol06 will look into that, fix the tests and resend :)

Thanks!

**Comment by ipeychev** [comment]
Great!

**Pull request closed without merging**
