### PR TITLE
Buttons that use richcombo update correctly values when it is rendered for the first time.

### PR DESCRIPTION
**Pull request by antoniopol06**

### CODE REVIEW

**Comment by antoniopol06** [comment]
With this fix, I am not sure if the name of the method cacheValue is correct because I use it into _setValue.

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Hey @antoniopol06,

What exactly are you concerns? Are there any other options?

Thanks,

**Comment by jbalsas** [comment]
Shouldn't we be rendering based on the state and not on the cached value [here](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/src/uibridge/richcombo.jsx#L109)?

**Comment by jbalsas** [comment]
Or was that what we had to do to support #515? In that case, the setState is there just to force a re-render?

**Comment by ipeychev** [comment]
Yes, that line of code was part of #515.

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/alloy-editor/compare/248f89a~2...248f89a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
